name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.c3feb8ac-01e5-4eb6-912e-5fe4a52e45b8}}
          heroku_app_name: "casekartin" #Must be unique in Heroku
          heroku_email: "selva08kujo@gmail.com"
